import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex py-2 mb-2 justify-between text-gray-300 font-bold gap-4 bg-primary">
          <div className=" ml-3 flex gap-4">
            <Link href="/">Home</Link>
            <Link href="/product">Product</Link>
          </div>
          <div className="mx-4">
            <Link href="/auth">Auth</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
